// <auto-generated />
using System;
using ItSupportServer.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItSupportServer.Data.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.AccountClaims", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("acc_id");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer")
                        .HasColumnName("claim_id");

                    b.HasKey("AccountId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("account_claims", (string)null);
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.AccountRoles", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("account_roles", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.AccountTokens", b =>
                {
                    b.Property<Guid>("AccountTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_token_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_time");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("AccountTokenId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_AccountTokens_created_at");

                    b.HasIndex("ExpiryTime");

                    b.ToTable("account_tokens", (string)null);
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Accounts", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("acc_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("current_points");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiredOtp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_otp");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int?>("LifetimePoints")
                        .HasColumnType("integer")
                        .HasColumnName("lifetime_points");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Otp")
                        .HasColumnType("text")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("AccountId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Accounts_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            FailedLoginAttempts = 0,
                            IsLocked = false,
                            Password = "$2a$12$UuDUXpLPwXBUMRJ8Grpz6.e7dnHvCJQ/SxAXqN.RC4Y2i0GR2Il9W",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Areas", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AreaId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Areas_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("areas", (string)null);

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Khu vực tiếp tân, phòng họp chính",
                            Name = "Tầng 1"
                        },
                        new
                        {
                            AreaId = 2,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Văn phòng làm việc phòng Kinh doanh, Kế toán",
                            Name = "Tầng 2"
                        },
                        new
                        {
                            AreaId = 3,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Văn phòng phòng CNTT, Server room",
                            Name = "Tầng 3"
                        },
                        new
                        {
                            AreaId = 4,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Phòng họp, khu vực đào tạo",
                            Name = "Tầng 4"
                        },
                        new
                        {
                            AreaId = 5,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Khu vực sản xuất, bảo trì thiết bị",
                            Name = "Nhà xưởng"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Causes", b =>
                {
                    b.Property<long>("CauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cause_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CauseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<long>("IssId")
                        .HasColumnType("bigint")
                        .HasColumnName("iss_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CauseId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Causes_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("IssId");

                    b.HasIndex("Name")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("causes", (string)null);

                    b.HasData(
                        new
                        {
                            CauseId = 1L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Bộ nguồn PSU bị hỏng hoặc dây nguồn lỏng",
                            IssId = 1L,
                            Name = "Nguồn điện hỏng"
                        },
                        new
                        {
                            CauseId = 2L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "RAM không nhận hoặc bị lỗi",
                            IssId = 1L,
                            Name = "RAM bị lỏng/hỏng"
                        },
                        new
                        {
                            CauseId = 3L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Bo mạch chủ bị chập cháy hoặc hỏng",
                            IssId = 1L,
                            Name = "Mainboard hỏng"
                        },
                        new
                        {
                            CauseId = 4L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Dây tín hiệu màn hình bị lỏng hoặc hỏng",
                            IssId = 2L,
                            Name = "Cáp VGA/HDMI lỏng"
                        },
                        new
                        {
                            CauseId = 5L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "VGA/GPU bị lỗi hoặc hỏng",
                            IssId = 2L,
                            Name = "Card đồ họa hỏng"
                        },
                        new
                        {
                            CauseId = 6L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Cáp Ethernet bị đứt hoặc tiếp xúc kém",
                            IssId = 5L,
                            Name = "Dây mạng bị đứt"
                        },
                        new
                        {
                            CauseId = 7L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Thiết bị mạng bị hỏng hoặc mất điện",
                            IssId = 5L,
                            Name = "Switch/Router hỏng"
                        },
                        new
                        {
                            CauseId = 8L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "IP tĩnh sai hoặc DHCP không cấp IP",
                            IssId = 5L,
                            Name = "Cấu hình IP sai"
                        },
                        new
                        {
                            CauseId = 9L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "File DLL thiếu hoặc bị corrupt",
                            IssId = 8L,
                            Name = "File hệ thống bị lỗi"
                        },
                        new
                        {
                            CauseId = 10L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Phiên bản cũ có bug, cần update",
                            IssId = 8L,
                            Name = "Phần mềm chưa update"
                        },
                        new
                        {
                            CauseId = 11L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Thông tin server SMTP không đúng",
                            IssId = 11L,
                            Name = "Cấu hình SMTP sai"
                        },
                        new
                        {
                            CauseId = 12L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Account email bị khóa do gửi spam hoặc vi phạm chính sách",
                            IssId = 11L,
                            Name = "Tài khoản email bị khóa"
                        },
                        new
                        {
                            CauseId = 13L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Máy nhiễm virus, phần mềm gián điệp",
                            IssId = 13L,
                            Name = "Virus/Malware"
                        },
                        new
                        {
                            CauseId = 14L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Dung lượng RAM không đủ cho ứng dụng",
                            IssId = 13L,
                            Name = "RAM không đủ"
                        },
                        new
                        {
                            CauseId = 15L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "HDD/SSD dung lượng >90%",
                            IssId = 13L,
                            Name = "Ổ cứng gần đầy"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Claims", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("claim_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim");

                    b.HasKey("ClaimId");

                    b.HasIndex("Claim")
                        .IsUnique();

                    b.ToTable("claims", (string)null);

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            Claim = "Admin"
                        },
                        new
                        {
                            ClaimId = 2,
                            Claim = "Area.View"
                        },
                        new
                        {
                            ClaimId = 3,
                            Claim = "Area.Create"
                        },
                        new
                        {
                            ClaimId = 4,
                            Claim = "Area.Edit"
                        },
                        new
                        {
                            ClaimId = 5,
                            Claim = "Area.Delete"
                        },
                        new
                        {
                            ClaimId = 6,
                            Claim = "Department.View"
                        },
                        new
                        {
                            ClaimId = 7,
                            Claim = "Department.Create"
                        },
                        new
                        {
                            ClaimId = 8,
                            Claim = "Department.Edit"
                        },
                        new
                        {
                            ClaimId = 9,
                            Claim = "Department.Delete"
                        },
                        new
                        {
                            ClaimId = 10,
                            Claim = "Employee.View"
                        },
                        new
                        {
                            ClaimId = 11,
                            Claim = "Employee.Create"
                        },
                        new
                        {
                            ClaimId = 12,
                            Claim = "Employee.Edit"
                        },
                        new
                        {
                            ClaimId = 13,
                            Claim = "Employee.Delete"
                        },
                        new
                        {
                            ClaimId = 14,
                            Claim = "Account.View"
                        },
                        new
                        {
                            ClaimId = 15,
                            Claim = "Account.Create"
                        },
                        new
                        {
                            ClaimId = 16,
                            Claim = "Account.Edit"
                        },
                        new
                        {
                            ClaimId = 17,
                            Claim = "Account.Delete"
                        },
                        new
                        {
                            ClaimId = 18,
                            Claim = "Role.View"
                        },
                        new
                        {
                            ClaimId = 19,
                            Claim = "Role.Create"
                        },
                        new
                        {
                            ClaimId = 20,
                            Claim = "Role.Edit"
                        },
                        new
                        {
                            ClaimId = 21,
                            Claim = "Role.Delete"
                        },
                        new
                        {
                            ClaimId = 22,
                            Claim = "IssueLog.View"
                        },
                        new
                        {
                            ClaimId = 23,
                            Claim = "IssueLog.Create"
                        },
                        new
                        {
                            ClaimId = 24,
                            Claim = "IssueLog.Edit"
                        },
                        new
                        {
                            ClaimId = 25,
                            Claim = "IssueLog.Delete"
                        },
                        new
                        {
                            ClaimId = 26,
                            Claim = "Issue.View"
                        },
                        new
                        {
                            ClaimId = 27,
                            Claim = "Issue.Create"
                        },
                        new
                        {
                            ClaimId = 28,
                            Claim = "Issue.Edit"
                        },
                        new
                        {
                            ClaimId = 29,
                            Claim = "Issue.Delete"
                        },
                        new
                        {
                            ClaimId = 30,
                            Claim = "Cause.View"
                        },
                        new
                        {
                            ClaimId = 31,
                            Claim = "Cause.Create"
                        },
                        new
                        {
                            ClaimId = 32,
                            Claim = "Cause.Edit"
                        },
                        new
                        {
                            ClaimId = 33,
                            Claim = "Cause.Delete"
                        },
                        new
                        {
                            ClaimId = 34,
                            Claim = "Device.View"
                        },
                        new
                        {
                            ClaimId = 35,
                            Claim = "Device.Create"
                        },
                        new
                        {
                            ClaimId = 36,
                            Claim = "Device.Edit"
                        },
                        new
                        {
                            ClaimId = 37,
                            Claim = "Device.Delete"
                        },
                        new
                        {
                            ClaimId = 38,
                            Claim = "DeviceType.View"
                        },
                        new
                        {
                            ClaimId = 39,
                            Claim = "DeviceType.Create"
                        },
                        new
                        {
                            ClaimId = 40,
                            Claim = "DeviceType.Edit"
                        },
                        new
                        {
                            ClaimId = 41,
                            Claim = "DeviceType.Delete"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Departments", b =>
                {
                    b.Property<int>("DptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dpt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DptId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DptId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Departments_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            DptId = 1,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Phòng Công nghệ thông tin - Quản lý hạ tầng IT, phát triển phần mềm",
                            Name = "Phòng CNTT"
                        },
                        new
                        {
                            DptId = 2,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Quản lý nhân sự, hành chính văn phòng",
                            Name = "Phòng Hành chính - Nhân sự"
                        },
                        new
                        {
                            DptId = 3,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Quản lý tài chính, kế toán doanh nghiệp",
                            Name = "Phòng Kế toán"
                        },
                        new
                        {
                            DptId = 4,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Phát triển kinh doanh, chăm sóc khách hàng",
                            Name = "Phòng Kinh doanh"
                        },
                        new
                        {
                            DptId = 5,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Sản xuất, bảo trì thiết bị kỹ thuật",
                            Name = "Phòng Kỹ thuật"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.DeviceTypes", b =>
                {
                    b.Property<int>("DeviceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("device_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceTypeId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_DeviceTypes_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("device_types", (string)null);

                    b.HasData(
                        new
                        {
                            DeviceTypeId = 1,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Desktop computer, PC, workstation",
                            Name = "Máy tính để bàn"
                        },
                        new
                        {
                            DeviceTypeId = 2,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Máy tính xách tay",
                            Name = "Laptop"
                        },
                        new
                        {
                            DeviceTypeId = 3,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Printer, máy in văn phòng",
                            Name = "Máy in"
                        },
                        new
                        {
                            DeviceTypeId = 4,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Máy photocopy, scan đa chức năng",
                            Name = "Máy photocopy"
                        },
                        new
                        {
                            DeviceTypeId = 5,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Monitor, màn hình máy tính",
                            Name = "Màn hình"
                        },
                        new
                        {
                            DeviceTypeId = 6,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Network switch, thiết bị chuyển mạch",
                            Name = "Switch mạng"
                        },
                        new
                        {
                            DeviceTypeId = 7,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Bộ định tuyến, router wifi",
                            Name = "Router"
                        },
                        new
                        {
                            DeviceTypeId = 8,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Máy chủ, server vật lý",
                            Name = "Server"
                        },
                        new
                        {
                            DeviceTypeId = 9,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Bộ lưu điện, uninterruptible power supply",
                            Name = "UPS"
                        },
                        new
                        {
                            DeviceTypeId = 10,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "IP Phone, điện thoại nội bộ",
                            Name = "Điện thoại IP"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Devices", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeviceId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("device_type_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Devices_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("Name")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("devices", (string)null);

                    b.HasData(
                        new
                        {
                            DeviceId = 1L,
                            Brand = "Dell",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 1,
                            Model = "OptiPlex 7090",
                            Name = "PC-IT-001",
                            Notes = "Máy trưởng phòng CNTT",
                            SerialNumber = "DELL-PC-001-2024"
                        },
                        new
                        {
                            DeviceId = 2L,
                            Brand = "HP",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 1,
                            Model = "EliteDesk 800 G8",
                            Name = "PC-KD-001",
                            Notes = "Máy phòng kinh doanh",
                            SerialNumber = "HP-PC-001-2024"
                        },
                        new
                        {
                            DeviceId = 3L,
                            Brand = "Lenovo",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 2,
                            Model = "ThinkPad X1 Carbon",
                            Name = "LT-IT-001",
                            Notes = "Laptop IT Support",
                            SerialNumber = "LN-LT-001-2024"
                        },
                        new
                        {
                            DeviceId = 4L,
                            Brand = "Dell",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 2,
                            Model = "Latitude 5420",
                            Name = "LT-KD-001",
                            Notes = "Laptop nhân viên kinh doanh",
                            SerialNumber = "DELL-LT-001-2024"
                        },
                        new
                        {
                            DeviceId = 5L,
                            Brand = "HP",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 3,
                            Model = "LaserJet Pro MFP M428fdw",
                            Name = "PRINTER-T1",
                            Notes = "Máy in tầng 1",
                            SerialNumber = "HP-PR-001-2024"
                        },
                        new
                        {
                            DeviceId = 6L,
                            Brand = "Canon",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 3,
                            Model = "imageRUNNER 2425",
                            Name = "PRINTER-T3",
                            Notes = "Máy in phòng CNTT tầng 3",
                            SerialNumber = "CN-PR-001-2024"
                        },
                        new
                        {
                            DeviceId = 7L,
                            Brand = "Cisco",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 6,
                            Model = "Catalyst 2960X",
                            Name = "SW-CORE-01",
                            Notes = "Core switch tầng 3 - Server room",
                            SerialNumber = "CISCO-SW-001-2024"
                        },
                        new
                        {
                            DeviceId = 8L,
                            Brand = "Cisco",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 7,
                            Model = "ISR 4331",
                            Name = "ROUTER-MAIN",
                            Notes = "Router chính kết nối internet",
                            SerialNumber = "CISCO-RT-001-2024"
                        },
                        new
                        {
                            DeviceId = 9L,
                            Brand = "Dell",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 8,
                            Model = "PowerEdge R750",
                            Name = "SRV-APP-01",
                            Notes = "Application server - Production",
                            SerialNumber = "DELL-SRV-001-2024"
                        },
                        new
                        {
                            DeviceId = 10L,
                            Brand = "HP",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DeviceTypeId = 8,
                            Model = "ProLiant DL380 Gen10",
                            Name = "SRV-DB-01",
                            Notes = "Database server - PostgreSQL",
                            SerialNumber = "HP-SRV-001-2024"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Employees", b =>
                {
                    b.Property<Guid>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("emp_id");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DptId")
                        .HasColumnType("integer")
                        .HasColumnName("dpt_id");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("emp_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EmpId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Employees_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DptId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("EmpCode")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("FullName")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmpId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AreaId = 1,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DptId = 1,
                            Email = "admin@itsupport.local",
                            EmpCode = "ADMIN001",
                            FullName = "System Administrator",
                            PhoneNumber = "0900000000"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogOperators", b =>
                {
                    b.Property<Guid>("IssLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("iss_log_id");

                    b.Property<Guid>("EmpId")
                        .HasColumnType("uuid")
                        .HasColumnName("emp_id");

                    b.Property<decimal?>("HoursSpent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("hours_spent");

                    b.Property<string>("OperatorRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operator_role");

                    b.HasKey("IssLogId", "EmpId");

                    b.HasIndex("EmpId");

                    b.ToTable("issue_log_operators", (string)null);
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogRequesters", b =>
                {
                    b.Property<long>("IssLogReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("iss_log_req_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IssLogReqId"));

                    b.Property<Guid?>("EmpId")
                        .HasColumnType("uuid")
                        .HasColumnName("emp_id");

                    b.Property<Guid>("IssLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("iss_log_id");

                    b.Property<string>("RequesterType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requester_type");

                    b.HasKey("IssLogReqId");

                    b.HasIndex("EmpId");

                    b.HasIndex("IssLogId");

                    b.ToTable("issue_log_requesters", (string)null);
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogs", b =>
                {
                    b.Property<Guid>("IssLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("iss_log_id");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<string>("Cause")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cause");

                    b.Property<long?>("CauseId")
                        .HasColumnType("bigint")
                        .HasColumnName("cause_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateReported")
                        .HasColumnType("date")
                        .HasColumnName("date_reported");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DptId")
                        .HasColumnType("integer")
                        .HasColumnName("dpt_id");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("issue_description");

                    b.Property<long?>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("operator");

                    b.Property<string>("PermanentFix")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("permanent_fix");

                    b.Property<string>("Requester")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("requester");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IssLogId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CauseId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_IssueLogs_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("DptId");

                    b.HasIndex("IssueId");

                    b.ToTable("issue_logs", (string)null);

                    b.HasData(
                        new
                        {
                            IssLogId = new Guid("22222222-2222-2222-2222-222222222221"),
                            AreaId = 2,
                            Cause = "Dây mạng bị đứt do bị kéo lê",
                            CauseId = 6L,
                            CreatedAt = new DateTime(2025, 10, 25, 9, 38, 50, 0, DateTimeKind.Utc),
                            DateReported = new DateOnly(2025, 10, 25),
                            DptId = 3,
                            IssueDescription = "Máy tính tại phòng kế toán không vào được mạng nội bộ",
                            IssueId = 5L,
                            Notes = "Đã cảnh báo user không kéo lê dây mạng",
                            Operator = "Nguyễn Văn A",
                            PermanentFix = "Dùng ống luồn dây để bảo vệ cáp mạng",
                            Requester = "Phòng Kế toán, Trần Thị B",
                            Resolution = "Thay dây mạng Cat6 mới, test kết nối OK",
                            Status = "Resolved"
                        },
                        new
                        {
                            IssLogId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AreaId = 1,
                            Cause = "Giấy bị ẩm do để gần cửa sổ",
                            CreatedAt = new DateTime(2025, 10, 27, 9, 38, 50, 0, DateTimeKind.Utc),
                            DateReported = new DateOnly(2025, 10, 27),
                            DptId = 2,
                            IssueDescription = "Máy in tầng 1 bị kẹt giấy liên tục",
                            IssueId = 4L,
                            Notes = "Đã hướng dẫn user cách xử lý kẹt giấy cơ bản",
                            Operator = "Nguyễn Văn A",
                            PermanentFix = "Di chuyển máy in ra xa cửa sổ, bảo quản giấy trong tủ kín",
                            Requester = "Phòng Hành chính, Lê Văn C",
                            Resolution = "Lấy giấy kẹt ra, thay giấy mới khô ráo",
                            Status = "Resolved"
                        },
                        new
                        {
                            IssLogId = new Guid("22222222-2222-2222-2222-222222222223"),
                            AreaId = 2,
                            Cause = "User tự đổi mật khẩu và quên",
                            CreatedAt = new DateTime(2025, 10, 29, 9, 38, 50, 0, DateTimeKind.Utc),
                            DateReported = new DateOnly(2025, 10, 29),
                            DptId = 4,
                            IssueDescription = "Nhân viên quên mật khẩu đăng nhập Windows",
                            IssueId = 10L,
                            Notes = "Đã gửi email hướng dẫn sử dụng LastPass cho toàn công ty",
                            Operator = "Nguyễn Văn A",
                            PermanentFix = "Hướng dẫn user sử dụng password manager",
                            Requester = "Phòng Kinh doanh, Phạm Thị D",
                            Resolution = "Reset mật khẩu Windows qua Active Directory",
                            Status = "Resolved"
                        },
                        new
                        {
                            IssLogId = new Guid("22222222-2222-2222-2222-222222222224"),
                            AreaId = 3,
                            Cause = "RAM 4GB không đủ cho Visual Studio + Docker",
                            CauseId = 14L,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            DateReported = new DateOnly(2025, 10, 30),
                            DptId = 1,
                            IssueDescription = "Laptop chạy rất chậm khi mở nhiều ứng dụng",
                            IssueId = 13L,
                            Notes = "Đã đề xuất mua thêm RAM cho 5 máy dev khác",
                            Operator = "Nguyễn Văn A",
                            PermanentFix = "Khuyến nghị tối thiểu 16GB RAM cho dev machine",
                            Requester = "Phòng CNTT, Hoàng Văn E",
                            Resolution = "Nâng cấp RAM từ 4GB lên 16GB",
                            Status = "In Progress"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Issues", b =>
                {
                    b.Property<long>("IssId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("iss_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IssId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IssId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Issues_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Name")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("issues", (string)null);

                    b.HasData(
                        new
                        {
                            IssId = 1L,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "PC/Laptop không lên nguồn hoặc không vào được Windows",
                            Name = "Máy tính không khởi động được",
                            Severity = 4
                        },
                        new
                        {
                            IssId = 2L,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Màn hình bị đen, không có tín hiệu",
                            Name = "Màn hình không hiển thị",
                            Severity = 3
                        },
                        new
                        {
                            IssId = 3L,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Bàn phím hoặc chuột không phản hồi",
                            Name = "Bàn phím/Chuột không hoạt động",
                            Severity = 2
                        },
                        new
                        {
                            IssId = 4L,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Máy in bị kẹt giấy, không in được",
                            Name = "Máy in bị kẹt giấy",
                            Severity = 2
                        },
                        new
                        {
                            IssId = 5L,
                            Category = "Network",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Không vào được internet, mất kết nối LAN",
                            Name = "Mất kết nối mạng",
                            Severity = 4
                        },
                        new
                        {
                            IssId = 6L,
                            Category = "Network",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Internet/Mạng nội bộ chậm, lag",
                            Name = "Kết nối mạng chậm",
                            Severity = 3
                        },
                        new
                        {
                            IssId = 7L,
                            Category = "Network",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Không tìm thấy hoặc không kết nối được mạng Wifi",
                            Name = "Không kết nối được Wifi",
                            Severity = 3
                        },
                        new
                        {
                            IssId = 8L,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Ứng dụng bị treo, thoát đột ngột",
                            Name = "Phần mềm bị lỗi/crash",
                            Severity = 3
                        },
                        new
                        {
                            IssId = 9L,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Lỗi khi cài đặt ứng dụng/phần mềm",
                            Name = "Không cài đặt được phần mềm",
                            Severity = 2
                        },
                        new
                        {
                            IssId = 10L,
                            Category = "Software",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Quên mật khẩu Windows, Email, ứng dụng nội bộ",
                            Name = "Quên mật khẩu",
                            Severity = 2
                        },
                        new
                        {
                            IssId = 11L,
                            Category = "Email",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Lỗi khi gửi hoặc nhận email",
                            Name = "Không gửi/nhận email được",
                            Severity = 4
                        },
                        new
                        {
                            IssId = 12L,
                            Category = "Email",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Mailbox đạt giới hạn dung lượng",
                            Name = "Email bị đầy dung lượng",
                            Severity = 2
                        },
                        new
                        {
                            IssId = 13L,
                            Category = "System",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "PC/Laptop chạy chậm, lag",
                            Name = "Máy tính chạy chậm",
                            Severity = 2
                        },
                        new
                        {
                            IssId = 14L,
                            Category = "System",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Màn hình xanh chết, Windows crash",
                            Name = "Blue Screen (BSOD)",
                            Severity = 5
                        },
                        new
                        {
                            IssId = 15L,
                            Category = "System",
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Dung lượng ổ cứng không đủ",
                            Name = "Ổ cứng đầy",
                            Severity = 3
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.PasswordResetTokens", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("TokenId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_password_reset_tokens_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_PasswordResetTokens_created_at");

                    b.HasIndex("Token")
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.HasIndex("ExpiresAt", "UsedAt")
                        .HasDatabaseName("ix_password_reset_tokens_expiry_status");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.RoleClaims", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer")
                        .HasColumnName("claim_id");

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("role_claims", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ClaimId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 26
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 30
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 34
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            ClaimId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 22
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 23
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 24
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 25
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 26
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 27
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 28
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 30
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 31
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 32
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            ClaimId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 22
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 26
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 30
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 34
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 38
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 6
                        },
                        new
                        {
                            RoleId = 4,
                            ClaimId = 2
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_Roles_deleted_at")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "System Administrator - Full access to all features",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Standard Employee - Create and manage issue logs",
                            Name = "Employee"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Department Manager - Extended permissions for team management",
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 10, 30, 9, 38, 50, 0, DateTimeKind.Utc),
                            Description = "Read-Only User - View reports and statistics",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.AccountClaims", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Accounts", "Account")
                        .WithMany("AccountClaims")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.Claims", "Claim")
                        .WithMany("AccountClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.AccountRoles", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Accounts", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.Roles", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.AccountTokens", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Accounts", "Account")
                        .WithMany("AccountTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Accounts", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Employees", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("ItSupportServer.Data.Models.Entities.Accounts", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Causes", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Issues", "Issues")
                        .WithMany("Causes")
                        .HasForeignKey("IssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Devices", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.DeviceTypes", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Employees", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Areas", "Area")
                        .WithMany("Employees")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.Departments", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogOperators", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Employees", "Employee")
                        .WithMany("IssueLogOperators")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.IssueLogs", "IssueLog")
                        .WithMany("IssueLogOperators")
                        .HasForeignKey("IssLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("IssueLog");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogRequesters", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Employees", "Employee")
                        .WithMany("IssueLogRequesters")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItSupportServer.Data.Models.Entities.IssueLogs", "IssueLog")
                        .WithMany("IssueLogRequesters")
                        .HasForeignKey("IssLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("IssueLog");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogs", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Areas", "Area")
                        .WithMany("IssueLogs")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.Causes", "CauseRef")
                        .WithMany("IssueLogs")
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItSupportServer.Data.Models.Entities.Departments", "Department")
                        .WithMany("IssueLogs")
                        .HasForeignKey("DptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.Issues", "Issue")
                        .WithMany("IssueLogs")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("CauseRef");

                    b.Navigation("Department");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.PasswordResetTokens", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Accounts", "Account")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.RoleClaims", b =>
                {
                    b.HasOne("ItSupportServer.Data.Models.Entities.Claims", "Claim")
                        .WithMany("RoleClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItSupportServer.Data.Models.Entities.Roles", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Accounts", b =>
                {
                    b.Navigation("AccountClaims");

                    b.Navigation("AccountRoles");

                    b.Navigation("AccountTokens");

                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Areas", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Causes", b =>
                {
                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Claims", b =>
                {
                    b.Navigation("AccountClaims");

                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Departments", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.DeviceTypes", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Employees", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("IssueLogOperators");

                    b.Navigation("IssueLogRequesters");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.IssueLogs", b =>
                {
                    b.Navigation("IssueLogOperators");

                    b.Navigation("IssueLogRequesters");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Issues", b =>
                {
                    b.Navigation("Causes");

                    b.Navigation("IssueLogs");
                });

            modelBuilder.Entity("ItSupportServer.Data.Models.Entities.Roles", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("RoleClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
